Controllers/AppsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using KisaanMart.Data;
using KisaanMart.Data.Models;
using Microsoft.AspNetCore.Http;
using System.IO;

namespace KisaanMart.Controllers
{
    public class AppsController : Controller
    {
        private readonly ApplicationContext _context;
        [HttpGet]
        public IActionResult LoadAppData()
        {
            try
            {
               
                // getting all Customer data  
                var apps = (from app in _context.Apps
                                select app);
                
                //Returning Json Data  
                return Json(new { data = apps });
                //return Json(new { data = data });

            }
            catch (Exception)
            {
                throw;
            }

        }
        public AppsController(ApplicationContext context)
        {
            _context = context;
        }

        // GET: Apps
        public async Task<IActionResult> Index()
        {
            return View(await _context.Apps.ToListAsync());
        }

        // GET: Apps/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var apps = await _context.Apps
                .FirstOrDefaultAsync(m => m.Id == id);
            if (apps == null)
            {
                return NotFound();
            }

            return View(apps);
        }

        // GET: Apps/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Apps/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,AppName,AppDescription,AppUrl,AppImage")] Apps apps, [FromForm(Name = "AppImage")] IFormFile AppImage)
        {
            if (ModelState.IsValid)
            {

                if (AppImage != null && AppImage.Length > 0)
                {
                    byte[] p1 = null;
                    using (var fs1 = AppImage.OpenReadStream())
                    using (var ms1 = new MemoryStream())
                    {
                        fs1.CopyTo(ms1);
                        p1 = ms1.ToArray();
                    }
                    apps.AppImage = p1;
                }
                _context.Add(apps);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            var query = from state in ModelState.Values
                        from error in state.Errors
                        select error.ErrorMessage;
            var errors = query.ToArray();
            return View(apps);
        }

        // GET: Apps/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var apps = await _context.Apps.FindAsync(id);
            if (apps == null)
            {
                return NotFound();
            }
            return View(apps);
        }

        // POST: Apps/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,AppName,AppDescription,AppUrl,AppImage")] Apps apps)
        {
            if (id != apps.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(apps);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AppsExists(apps.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(apps);
        }

        // GET: Apps/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var apps = await _context.Apps
                .FirstOrDefaultAsync(m => m.Id == id);
            if (apps == null)
            {
                return NotFound();
            }

            return View(apps);
        }

        // POST: Apps/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var apps = await _context.Apps.FindAsync(id);
            _context.Apps.Remove(apps);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AppsExists(int id)
        {
            return _context.Apps.Any(e => e.Id == id);
        }
    }
}

Views/Apps/Create.cshtml
@model KisaanMart.Data.Models.Apps

@{
    ViewData["Title"] = "Create";
}




<hr />
<div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
        <h1>Agriculture Apps</h1>
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="AppName" class="control-label"></label>
                <input asp-for="AppName" class="form-control" />
                <span asp-validation-for="AppName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AppDescription" class="control-label"></label>
                @*<input asp-for="AppDescription" class="form-control" />*@
                <textarea asp-for="AppDescription" class="form-control" rows="5" cols="40"></textarea>
                <span asp-validation-for="AppDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AppUrl" class="control-label"></label>
                <input asp-for="AppUrl" class="form-control" />
                <span asp-validation-for="AppUrl" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                <label asp-for="AppImage" class="control-label"></label>
                <input asp-for="AppImage" class="form-control" />
                <span asp-validation-for="AppImage" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="AppImage" class="control-label"></label>
                <input type="file" name="AppImage" id="AppImage" class="form-control">
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
    <div class="col-md-4"></div>
</div>

    <div>
        <a asp-action="Index" class="btn btn-info">Back to Apps</a>
    </div>

Views/Apps/Delete.cshtml
@model KisaanMart.Data.Models.Apps

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Apps</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AppName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AppName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AppDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AppDescription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AppUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AppUrl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AppImage)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AppImage)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Apps/Details.cshtml
@model KisaanMart.Data.Models.Apps

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Apps</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AppName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AppName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AppDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AppDescription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AppUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AppUrl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AppImage)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AppImage)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Apps/Edit.cshtml
@model KisaanMart.Data.Models.Apps

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Apps</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="AppName" class="control-label"></label>
                <input asp-for="AppName" class="form-control" />
                <span asp-validation-for="AppName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AppDescription" class="control-label"></label>
                <input asp-for="AppDescription" class="form-control" />
                <span asp-validation-for="AppDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AppUrl" class="control-label"></label>
                <input asp-for="AppUrl" class="form-control" />
                <span asp-validation-for="AppUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AppImage" class="control-label"></label>
                <input asp-for="AppImage" class="form-control" />
                <span asp-validation-for="AppImage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Apps/Index.cshtml
@model IEnumerable<KisaanMart.Data.Models.Apps>

@{
    ViewData["Title"] = "Index";
}

<div class="container">
    <br />
    <p>
        <a class="btn btn-info" asp-action="Create">Add New App</a>
    </p>
    <div style="width:90%; margin:0 auto;">
        <table id="example" class="table table-light table-striped table-bordered dt-responsive nowrap" cellspacing="0">
            <thead>
                <tr>
                    <th>Image</th>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Edit Item</th>
                    <th>Delete Item</th>
                </tr>
            </thead>
        </table>
    </div>
</div>
@section Scripts {
    <script>
        $(document).ready(function ()
        {
            $("#example").DataTable({
                "processing": true, // for show progress bar
                "serverSide": true, // for process server side
                "filter": true, // this is for disable filter (search box)
                "orderMulti": false, // for disable multiple column at once
                "paging":false,
                "ajax": {
                    "url": "/Apps/LoadAppData",
                    "type": "GET",
                    "datatype": "json"

                },
                "columnDefs":
                [{
                    //"targets": [0],
                    //"visible": false,
                    //"searchable": false
                }],
                "columns": [
                    {
                            "render": function (data, type, full, meta) {
                                return '<img style="width:90px;height:90px;" src="data:image/png;base64,' + full.AppImage + '">';
                            }
                        },
                    { "data": "AppName"},
                    { "data": "AppDescription" },                   
                    {
                        "render": function (data, type, full, meta)
                        { return '<a class="btn btn-info" href="/Apps/Edit/' + full.Id + '">Edit</a>'; }
                    },
                    {
                        data: null, render: function (data, type, row)
                        {
                            return "<a href='#' class='btn btn-danger' onclick=DeleteData('" + row.Id + "'); >Delete</a>" ;
                                       }
                     },


                ]

            });
        });


    function DeleteData(MachineID)
        {
         if (confirm("Are You sure to delete this record..?")) {
        $.ajax({
            type: 'POST',
            url: '@Url.Action("Delete", "Apps")',
           data: { id: MachineID },
           datatype: 'json',
           success: function (response) {
               oTable = $('#example').DataTable();
               oTable.draw();
           },
           error: function (msg) {
               alert(msg.responseText);
           }
       });
    }
        }



    </script>
}