Controllers/MachinesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Dynamic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using KisaanMart.Data;
using KisaanMart.Data.Models;
using Microsoft.AspNetCore.Http;
using System.IO;

namespace KisaanMart.Controllers
{
    public class MachinesController : Controller
    {
        private readonly ApplicationContext _context;

        public MachinesController(ApplicationContext context)
        {
            _context = context;
        }

        // GET: Machines
        public async Task<IActionResult> Index()
        {
            return View(await _context.Machines.ToListAsync());
        }
        public JsonResult GetMachines()
        {
            
            var query = (from c in _context.Machines
                         select new SelectListItem()
                         {
                             Value = c.Id.ToString(),
                             Text = c.MachineName
                         });
            return new JsonResult(query.ToList());
        }

        public IActionResult LoadMachineData()
        {
            try
            {
                var draw = HttpContext.Request.Form["draw"].FirstOrDefault();

                // Skip number of Rows count  
                var start = Request.Form["start"].FirstOrDefault();

                // Paging Length 10,20  
                var length = Request.Form["length"].FirstOrDefault();

                // Sort Column Name  
                var sortColumn = Request.Form["columns[" + Request.Form["order[0][column]"].FirstOrDefault() + "][name]"].FirstOrDefault();

                // Sort Column Direction (asc, desc)  
                var sortColumnDirection = Request.Form["order[0][dir]"].FirstOrDefault();

                // Search Value from (Search box)  
                var searchValue = Request.Form["search[value]"].FirstOrDefault();

                //Paging Size (10, 20, 50,100)  
                int pageSize = length != null ? Convert.ToInt32(length) : 0;

                int skip = start != null ? Convert.ToInt32(start) : 0;

                int recordsTotal = 0;

                // getting all Customer data  
                var machines = (from machine in _context.Machines
                                    select machine);
                //Sorting  
                if (!(string.IsNullOrEmpty(sortColumn) && string.IsNullOrEmpty(sortColumnDirection)))
                {
                    //machines = machines.OrderBy(sortColumn + " " + sortColumnDirection);
                    //machines= (sortColumnDirection == "ASC") ? machines.OrderBy(sortColumn).AsQueryable() : machines.OrderByDescending(sortColumn).AsQueryable()
                }
                //Search  
                if (!string.IsNullOrEmpty(searchValue))
                {
                    machines = machines.Where(m => m.MachineName.Contains(searchValue));
                }

                //total number of rows counts   
                recordsTotal = machines.Count();
                //Paging   
                var data = machines.Skip(skip).Take(pageSize).ToList();
                //Returning Json Data  
                return Json(new { draw = draw, recordsFiltered = recordsTotal, recordsTotal = recordsTotal, data = data });
                //return Json(new { data = data });

            }
            catch (Exception)
            {
                throw;
            }

        }
        // GET: Machines/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var machine = await _context.Machines
                .FirstOrDefaultAsync(m => m.Id == id);
            if (machine == null)
            {
                return NotFound();
            }

            return View(machine);
        }

        // GET: Machines/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Machines/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,MachineName,MachineDescription,MachineImage")] Machine machine, [FromForm(Name = "MachineImage")] IFormFile MachineImage)
        {
            if (ModelState.IsValid)
            {
                if (MachineImage != null && MachineImage.Length > 0)
                {
                    byte[] p1 = null;
                    using (var fs1 = MachineImage.OpenReadStream())
                    using (var ms1 = new MemoryStream())
                    {
                        fs1.CopyTo(ms1);
                        p1 = ms1.ToArray();
                    }
                    machine.MachineImage = p1;
                }
                _context.Add(machine);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(machine);
        }
        public async Task<ActionResult> RenderImage(int id)
        {
            Machine item = await _context.Machines.FindAsync(id);

            byte[] photoBack = item.MachineImage;

            return File(photoBack, "image/png");
        }
        // GET: Machines/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var machine = await _context.Machines.FindAsync(id);
            if (machine == null)
            {
                return NotFound();
            }
            return View(machine);
        }

        // POST: Machines/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,MachineName,MachineDescription")] Machine machine)
        {
            if (id != machine.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    //machine.MachineImage = Convert.ToBase64String(MachineImage);
                    _context.Update(machine);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MachineExists(machine.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(machine);
        }

        // GET: Machines/Delete/5
        //public async Task<IActionResult> Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var machine = await _context.Machines
        //        .FirstOrDefaultAsync(m => m.Id == id);
        //    if (machine == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(machine);
        //}

        // POST: Machines/Delete/5
        [HttpPost]
        
        public async Task<IActionResult> Delete(int id)
        {
            var machine = await _context.Machines.FindAsync(id);
            _context.Machines.Remove(machine);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MachineExists(int id)
        {
            return _context.Machines.Any(e => e.Id == id);
        }
    }
}

Controllers/WorkersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using KisaanMart.Data;
using KisaanMart.Data.Models;

namespace KisaanMart.Controllers
{
    public class WorkersController : Controller
    {
        private readonly ApplicationContext _context;

        public WorkersController(ApplicationContext context)
        {
            _context = context;
        }

        // GET: Workers
        public async Task<IActionResult> Index()
        {
            return View(await _context.Workers.ToListAsync());
        }

        // GET: Workers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var worker = await _context.Workers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (worker == null)
            {
                return NotFound();
            }

            return View(worker);
        }

        // GET: Workers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Workers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,UserName,UserPhoneNo")] Worker worker)
        {
            if (ModelState.IsValid)
            {
                _context.Add(worker);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(worker);
        }

        // GET: Workers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var worker = await _context.Workers.FindAsync(id);
            if (worker == null)
            {
                return NotFound();
            }
            return View(worker);
        }

        // POST: Workers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,UserName,UserPhoneNo")] Worker worker)
        {
            if (id != worker.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(worker);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!WorkerExists(worker.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(worker);
        }

        // GET: Workers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var worker = await _context.Workers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (worker == null)
            {
                return NotFound();
            }

            return View(worker);
        }

        // POST: Workers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var worker = await _context.Workers.FindAsync(id);
            _context.Workers.Remove(worker);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool WorkerExists(int id)
        {
            return _context.Workers.Any(e => e.Id == id);
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title style="font-family:Algerian;font-weight:bold;font-style:italic">@ViewData["Title"] - Kisaanvaradhi</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link href="~/lib/font-awesome/css/all.css" rel="stylesheet" />
        <link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css" rel="stylesheet" />
        <link href="https://cdn.datatables.net/responsive/2.1.1/css/responsive.bootstrap.min.css" rel="stylesheet" />
        @*<link href="~/lib/font-awesome/css/bootstrap.css" rel="stylesheet" />
        <link href="~/lib/font-awesome/css/responsive.bootstrap.css" rel="stylesheet" />*@
        <link href="~/lib/font-awesome/css/all.css" rel="stylesheet" />

        <link href="~/css/slick.css" rel="stylesheet" />
        <link href="~/css/slick-theme.css" rel="stylesheet" />
    </environment>
    <environment exclude="Development">
        @*<link href="~/lib/font-awesome/css/bootstrap.css" rel="stylesheet" />
        <link href="~/lib/font-awesome/css/responsive.bootstrap.css" rel="stylesheet" />*@
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
        <link href="~/css/slick.css" rel="stylesheet" />

        <link href="~/css/slick-theme.css" rel="stylesheet" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>

    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/Images/KisaanTractor.png" alt="Company logo" width="30" height="30" />
                    Kisaanvaradhi
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index"><span class="fa fa-home"></span> Home</a>
                        </li>
                        @*@if (!User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Register" asp-action="Create">Register</a>
                            </li>
                        }*@
                        @if (!User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                        }
                        @*@if (User.Identity.IsAuthenticated)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Machines" asp-action="Index">Machines info</a>
                                </li>
                            }*@
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="UserMachines" asp-action="Create">Rent machinery</a>
                            </li>
                        }
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Transactions" asp-action="Create">Request machinery</a>
                            </li>
                        }


                        @if (User.IsInRole("Moderator"))
                        {
                            @if (User.Identity.IsAuthenticated)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="User" asp-action="Index">Manage my users</a>
                                </li>
                            }

                        }
                        @if (User.IsInRole("Moderator"))
                        {
                            @if (User.Identity.IsAuthenticated)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Workers" asp-action="Index">Manage workforce</a>
                                </li>
                                <li class="nav-item">
                                    
                                    @*<a class="nav-link text-light" asp-area="" asp-controller="Workers" asp-action="Index">Manage workforce</a>*@
                                </li>
                            }
                        }

                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item dropdow ml-auto">
                                <a class="nav-link dropdown-toggle " href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color:white">
                                    @if (@HttpContextAccessor.HttpContext.Session.GetString("UserName") == "")
                                    {
                                        @HttpContextAccessor.HttpContext.Session.GetString("UserPhoneNo")
                                    }
                                    else
                                    {
                                        @HttpContextAccessor.HttpContext.Session.GetString("UserName")
                                    }
                                </a>
                                <div class="dropdown-menu dropdown-menu-right position-absolute" aria-labelledby="navbarDropdown">
                                    @if (User.IsInRole("Moderator"))
                                    {
                                        <span class="dropdown-item">My Credits: @HttpContextAccessor.HttpContext.Session.GetString("AccumulatedPoints")</span>
                                    }
                                        <a class="dropdown-item" asp-controller="Transactions" asp-action="Index">My Dashboard</a>
                                        <a class="dropdown-item" asp-area="" asp-controller="User" asp-action="Edit">Edit Profile</a>
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" asp-action="Logout" asp-controller="Account"><span class="fa fa-sign-out"></span>Logout</a>
                                    </div>
                            </li>
                        }


                    </ul>



                </div>
            </div>
        </nav>
    </header>
    @*<div class="container">*@
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>



    <environment include="Development">

        @*<script src="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.0.1/build/ol.js"></script>
        <script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
        <script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap4.min.js "></script>*@
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
        <script src="~/lib/font-awesome/js/all.js"></script>
        <script src="~/lib/font-awesome/js/ol.js"></script>
        <script src="~/lib/font-awesome/js/datatables.js"></script>
        <script src="~/lib/font-awesome/js/bootstrap.js"></script>

        <script src="~/js/modernizr.custom.86080.js"></script>

        <script src="~/js/jssor.slider-22.0.15.mini.js"></script>


    </environment>
    <environment exclude="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
        <script src="~/lib/font-awesome/js/all.js"></script>
        <script src="~/lib/font-awesome/js/ol.js"></script>
        <script src="~/lib/font-awesome/js/datatables.js"></script>
        <script src="~/lib/font-awesome/js/bootstrap.js"></script>
        <script src="~/js/jssor.slider-22.0.15.mini.js"></script>
        

       

    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>
<style>
    body {
        background-image: linear-gradient(to bottom, rgba(0, 100, 0, 0.32), rgba(0, 150, 0, 0.73)),url('../Images/KisaanImg.jpg');
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-size: cover;
        margin: 0px;
        color: white;
    }
</style>